### ISSUE TITLE
Documentation not up-to-date?

### ISSUE THREAD

**Issue by pepejeria** [objectbox/objectbox-swift#11]
A store should be created in the following way according to the [getting started guide](https://swift.objectbox.io/getting-started):
`let store = Store(directoryPath: "/path/to/the/store")`

Note though that Store throws so Xcode will correctly show the following error:
`Call can throw, but it is not marked with 'try' and the error is not handled`

It would also be great to provide a real directory path suggestion for the Store constructor.

**Comment by uli-objectbox** [comment]
I've fixed the missing `try`, will see if I can find a simple way to get at a correct path that doesn't distract from the actual task of creating a store.

**Comment by uli-objectbox** [comment]
I just fixed the example Store path in the docs for the next release. Thank you for drawing my attention to it.

**Comment by uli-objectbox** [comment]
The fixed documentation is live now. Thank you again for bringing this to our attention.

**Comment by seljabali** [comment]
I'm similarly unsure how to create a `Store` @uli-objectbox using the latest version: `0.9.1`

```swift
/// Create a new store.
/// - Parameter model: A model description generated using ObjectBox.modelBuilder
/// - Parameter directory: The path to thedirectory in which ObjectBox is to save the files related to the database.
/// - Parameter maxDbSizeInKByte: Maximum size the database may take up on disk.
/// - Parameter fileMode: The unix permissions (like 0o755) to use for creating the database files.
/// - Parameter maxReaders: How many threads may be reading at the same time at once.
public init(model: OpaquePointer, directory: String, maxDbSizeInKByte: UInt64, fileMode: UInt32, maxReaders: UInt32)
```


- How can we pass in this `model`?
- I'm a bit curious how passing in the `fileMode`, when would a developer want anything besides read, write, execute for owner?

**Comment by uli-objectbox** [comment]
You can check out the example app included with the code to see how it's done. In short, you don't need to bother about the model. The code generator will create an extension on `Store` for you without the model parameter, which will set up your model correctly for you.

**Comment by Burtan** [comment]
The Store constructor with only the path is private and cannot be used?

**Comment by uli-objectbox** [comment]
@seljabali If you're still not able to use the generated constructor, please let me know in #15 (which also contains more attempts by me to explain how it should work).
