### ISSUE TITLE
Generated entity metadata extensions triggers SwiftLint error

### ISSUE THREAD

**Issue by pepejeria** [objectbox/objectbox-swift#12]
<img width="1164" alt="Screen Shot 2019-06-07 at 19 29 00" src="https://user-images.githubusercontent.com/1394550/59122284-ae8c4100-895a-11e9-9587-a710b5d66355.png">

Nitpick: Nice to see that `// swiftlint:disable all` is added to the top of the generated file, but the two lines above trigger a `vertical_whitespace` warning. 

I can add this folder to the `excluded` in the `.swiftlint.yml` file, but would be even better if ObjectBox can avoid adding that extra line.

**Comment by uli-objectbox** [comment]
Thanks for the shout-out, I've fixed it for the next release.

**Comment by uli-objectbox** [comment]
The release with the fix is out now.
