### ISSUE TITLE
Does not work if Project Name has a space in it.

### ISSUE THREAD

**Issue by bortka** [objectbox/objectbox-swift#14]
Seems to look for /generated/generated instead of generated

**Comment by uli-objectbox** [comment]
I just tried it again and it works fine for me. Can you provide the steps you made and what error messages you received?

I did the following:

- Create a new Xcode project from the macOS Application template
- Created podfile using pod init
- added `pod 'ObjectBox'` to the podfile
- ran `pod install` and `Pods/ObjectBox/setup.rb`
- added a simple entity with ID and one property to the project
- Built the project

It found all the files, and the app ran. What did you do differently to reproduce the failure?

**Comment by uli-objectbox** [comment]
I think I just fixed an issue that has the same symptoms as yours. Try leaving away the project name and just running the script without parameters (if you are using CocoaPods). This should be fixed in an upcoming release.

**Comment by uli-objectbox** [comment]
The 1.0 release includes a fix to `setup.rb` that caused setup to use a wrong path if you were calling the script with the project name (as we recommended) instead of passing no project name and letting it find the project by itself.
