### ISSUE TITLE
No example for how to use 0.9 Store() constructor

### ISSUE THREAD

**Issue by bortka** [objectbox/objectbox-swift#15]
Documentation shows:
    /// Create a new store.
    /// - Parameter model: A model description generated using ObjectBox.modelBuilder
    /// - Parameter directory: The path to thedirectory in which ObjectBox is to save the files related to the database.
    /// - Parameter maxDbSizeInKByte: Maximum size the database may take up on disk.
    /// - Parameter fileMode: The unix permissions (like 0o755) to use for creating the database files.
    /// - Parameter maxReaders: How many threads may be reading at the same time at once.

but no examples of how to use ObjectBox.modelBuilder

**Comment by uli-objectbox** [comment]
The code generator will generate that code for you, so you should generally not need to use the model builder, or that `Store` constructor. 

That said, there should be Swift documentation comments in the `EntityBuilder` and `ModelBuilder` headers, if you're curious.

**Comment by deniswindover** [comment]
Sorry, but there is only one constructor and it doesn't give to init store without all params!

**Comment by deniswindover** [comment]
![Снимок экрана 2019-09-13 в 21 13 08](https://user-images.githubusercontent.com/36079082/64884873-67a19c00-d66b-11e9-9c86-29d60e9f7ed5.png)

**Comment by uli-objectbox** [comment]
How are you installing ObjectBox in your project? Did you use the `setup.rb` script? That should install a shell script build phase in your project that will call upon our code generator to generate the init method for you.

You find the init method in the `generated/EntityInfo-PROJECTNAME.generated.swift` file that the code generator produces. The method signature looks like this:

```
convenience init(directoryPath: String, maxDbSizeInKByte: UInt64 = 1024 * 1024, fileMode: UInt32 = 0o755, maxReaders: UInt32 = 0) throws {
```

How did you set up your project?

**Comment by uli-objectbox** [comment]
The error above looks like the code generator is not being run, or the `generated/EntityInfo-PROJECTNAME.generated.swift` file hasn't been added to your target.

**Comment by uli-objectbox** [comment]
In case you had issues using the `setup.rb` script, the 1.0 release has fixed a few issues in that area if you're not using CocoaPods. Let me know if you encounter any issues.
