### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by toanbuidjv** [objectbox/objectbox-swift#47]
"Type 'Author' does not conform to protocol 'EntityInspectable'
"Type 'Note' does not conform to protocol 'EntityInspectable'"
....
Please fix error help me
<img width="1516" alt="Screen Shot 2021-01-07 at 10 03 25 AM" src="https://user-images.githubusercontent.com/75288800/103845905-9e58bc80-50cf-11eb-8cfb-ef2690ae56d9.png">
Xcode 12.2, iOS 14.2

**Comment by massimopasquali** [comment]
Hi,

I have same problem, have solved? Could you explain me how you have done?
