### ISSUE TITLE
Error on compiling for Mac Catalyst

### ISSUE THREAD

**Issue by ussu99** [objectbox/objectbox-swift#62]
Trying to Compile my Project with Target Mac Catalyst but getting error shown below:
  
Does objectBox Supports Compiling for Mac Catalyst? Should I use the Manual Method described in link below?
https://swift.objectbox.io/advanced/manual-installation

#### Error on Xcode Compile
```
Showing All Messages
...Pods/ObjectBox/ObjectBox.xcframework:1:1: While building for Mac Catalyst, no library for this platform was found in '/Users/q/Ed/Projects/GIT/personalscrum/Pods/ObjectBox/ObjectBox.xcframework'.
```

- ObjectBox version 1.7.0
 - Installed via pod file
#### Podfile
```
target 'XYFramework' do
pod 'ObjectBox' 
end
```

**Comment by greenrobot-team** [comment]
The ObjectBox pod is compatible with macOS, so I don't see why it wouldn't work.

If anyone is still affected, please share additional details in a new issue. Maybe even a small example project so we can reproduce this. Will close this as it was reported for a rather old version.
