### ISSUE TITLE
how to unistall objectbox-swift from project

### ISSUE THREAD

**Issue by mizhiqiang** [objectbox/objectbox-swift#63]

**Comment by greenrobot-team** [comment]
If you [installed as recommended via a pod](https://github.com/objectbox/objectbox-swift#adding-objectbox-to-your-project) (CocoaPods), then based on a quick Google search it should be enough to remove the `pod 'ObjectBox'` line from your `Podfile` and run `pod install` again.

Let me know if that doesn't work.

**Comment by greenrobot-team** [comment]
Full instructions:

Remove the `pod 'ObjectBox'` line from your `Podfile` and run `pod install` again.

Revert the changes made to the Xcode project by [the `setup.rb` script](https://github.com/objectbox/objectbox-swift/blob/main/Source/ios-framework/cocoapod/setup.rb):
- Remove the group containing the files generated by ObjectBox.
- Remove the build phase related to ObjectBox (prefixed by `[OBX]`).
