### ISSUE TITLE
Xcode 14 beta 4 build phase script warning

### ISSUE THREAD

**Issue by funcJeff** [objectbox/objectbox-swift#66]
In Xcode 14 beta 4 (14A5284g), building a toy example project will output this warning:

```
warning: Run script build phase '[OBX] Update Sourcery Generated Files' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'MyApp' from project 'MyApp')
```

I followed second instruction, and went to _Target > Build Phases > \[OBX\] Update Sourcery Generated Files_ and unchecked  "Based on dependency analysis". That made the warning go away on next build.

I surmise that is the correct fix, yes?

**Comment by greenrobot-team** [comment]
Sorry, we haven't tested with this (pre-release) version of XCode, yet. I guess following the instructions as written to run every build does no harm at this point.

**Comment by greenrobot-team** [comment]
Changed the `setup.rb` script to uncheck the "Based on dependency analysis" which downgrades this from a warning to a note.

Will probably ship with release `1.9.1`.
