### ISSUE TITLE
SYNC to DB form ios ??

### ISSUE THREAD

**Issue by sravan136** [objectbox/objectbox-swift#77]
:rotating_light: First, please check:
 - existing issues,
 - Docs https://swift.objectbox.io/
 - FAQ page https://swift.objectbox.io/faq

Start with a clear and concise description of what problem you are trying to solve.
Often there is already a solution! 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context (e.g. platform or language) about the feature request here.

**Comment by greenrobot-team** [comment]
Sync related documentation is at https://sync.objectbox.io/. Let us know if you are missing something specifically.
