### ISSUE TITLE
对比wcdb 的速度差异？

### ISSUE THREAD

**Issue by NBXXF** [objectbox/objectbox-swift#79]
:rotating_light: First, please check:
 - existing issues,
 - Docs https://swift.objectbox.io/
 - FAQ page https://swift.objectbox.io/faq

Start with a clear and concise description of what problem you are trying to solve.
Often there is already a solution! 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context (e.g. platform or language) about the feature request here.

**Comment by greenrobot-team** [comment]
@NBXXF Please post in English so everyone can understand. Also please fill out the issue template. Thanks!

**Comment by greenrobot-team** [comment]
To answer: we have done no benchmarks to compare against "wcdb".

[We have a Flutter benchmark app](https://github.com/objectbox/objectbox-dart#flutter-database-performance-benchmarks) that uses objectbox-swift behind the scenes on iOS.
