### ISSUE TITLE
Support vector index (HNSW index)

### ISSUE THREAD

**Issue by eakarsu** [objectbox/objectbox-swift#85]
I am developing on iOS a RAG system with objectbox vector database within swift binding. But documentation is not synced with code. I can not run any example. I will index only text data. Can you point me right direction?

Thanks

**Comment by greenrobot-team** [comment]
The ObjectBox Swift library currently does not support creating a vector index.

You might want to check out the [ObjectBox Dart/Flutter library](https://pub.dev/packages/objectbox) which supports this. [Examples in the docs](https://docs.objectbox.io/on-device-vector-search).

**Comment by greenrobot-team** [comment]
Vector search (HNSW index) is now supported as of version 4.0.0. See https://docs.objectbox.io/on-device-vector-search for examples.
