### ISSUE TITLE
User script sandboxing breaks with generate_sources.sh

### ISSUE THREAD

**Issue by colintheshots** [objectbox/objectbox-swift#87]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-swift/issues)

### Build info

- ObjectBox version: 4.0.0
- OS: iOS 16
- Device/chipset: iPhone 15 Pro

### Steps to reproduce

1. Install Cocoapods into app following recommended instructions: add to Podfile, pod install --repo-update
2. Run setup Ruby script to install Sourcery code gen script
3. Run project on iOS

### Expected behavior

The app builds, running the code gen script.

### Actual behavior

The app fails to build with the message "Sandbox: zsh(96617) deny(1) file-read-data ...app/Pods/ObjectBox/Mac/OBXCodeGen.framework/Versions/A/Resources/generate_sources.sh"

### Code

No code needed, just a template iOS app.

### Logs, stack traces

<details><summary>Logs</summary>

```console
error: Sandbox: zsh(96617) deny(1) file-read-data ...app/Pods/ObjectBox/Mac/OBXCodeGen.framework/Versions/A/Resources/generate_sources.sh (in target 'App' from project 'app')
/bin/zsh: can't open input file: ...app/Pods/ObjectBox/generate_sources.sh
```

</details>

### Workaround

I've noticed that I can workaround the issue by disabling User Script Sandboxing in Build Settings on the app target. Ideally, this wouldn't be necessary.

If it is necessary, this should be mentioned in the instructions to install the Pod.

**Comment by rupe120** [comment]
I am seeing the same

**Comment by greenrobot-team** [comment]
Thanks for reporting! I guess "User Script Sandboxing" is turned on by default now.

As suggested, we should add a step to the installation instructions to turn this off, or maybe let the setup.rb script do it.

The current workaround is to manually disable "User Script Sandboxing" in Build Settings of the Xcode project.

**Comment by greenrobot-team** [comment]
This is now documented on the Installing ObjectBox page: https://swift.objectbox.io/install#project-settings

(Side note: future versions of the generator may lift this requirement. But it's required right now.)
