### ISSUE TITLE
Missing required module 'ObjectBoxC'

### ISSUE THREAD

**Issue by Zpecter** [objectbox/objectbox-swift#9]
## Issue Basics

App can't compile after upgradin ObjectBox version to 0.8.0

- ObjectBox version (are using the latest version?): 0.8.0

### Reproducing the bug
**Description**

I have just updated to version 0.8.0, and it doesn't compile the project.

```
Error: missing required module 'ObjectBoxC'
```

**Comment by uli-objectbox** [comment]
Investigating.

**Comment by uli-objectbox** [comment]
All right, it was an issue with the module maps. I've pushed 0.8.1 which simply stops using module maps and fixes it that way.

**Comment by Zpecter** [comment]
It works again, thank you very much.
